spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

app:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    port: ${MINIO_PORT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}
  auth:
    jwt:
      secret: ${APP_AUTH_JWT_SECRET}
      access-token-expiration-seconds: ${APP_AUTH_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS}
      refresh-token-expiration-seconds: ${APP_AUTH_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS}
      issuer: ${APP_AUTH_JWT_ISSUER}
    kakao:
      client-id: ${APP_AUTH_KAKAO_CLIENT_ID}
      client-secret: ${APP_AUTH_KAKAO_CLIENT_SECRET}
      redirect-uris: ${APP_AUTH_KAKAO_REDIRECT_URI}
      token-uri: ${APP_AUTH_KAKAO_TOKEN_URI}
      user-info-uri: ${APP_AUTH_KAKAO_USER_INFO_URI}
